spring:
  application:
    name: employee-manager-be

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: ${DB_DRIVER_CLASS:org.postgresql.Driver}

  flyway:
    enabled: true
    create-schemas: true
    default-schema: ${DB_DEFAULT_SCHEMA:company}